import { __ } from "@wordpress/i18n";
import { TemplateOneSvg } from "./icons";

const textDomain = 'xpo-block';

export const templateData = {
  title: __('Select Table of Contents Template', textDomain),
  subtitle: __('Choose a design template for your table of contents.', textDomain),
  templates: [
    {
      id: 'template-1',
      label: __('Template 1', textDomain),
      tag: __('Classic Table of Contents', textDomain),
      icon: TemplateOneSvg,
      attributes: {
        titleText: __('Table of Contents', textDomain),
        contentTitle: __('The Ultimate Guide to Modern Web Development', textDomain),
        contentSubtitle: __('Explore key concepts, architecture, design patterns, and performance optimization techniques for modern web applications.', textDomain),
        items: [
          { id: '', title: 'Understanding Modern Web Architecture', level: 2, paragraph: 'An overview of client-server models, microservices, micro-frontends, and serverless architectures.' },
          { id: '', title: 'Frontend Fundamentals', level: 2, paragraph: 'Core technologies driving modern user interfaces and user experience across responsive devices.' },
          { id: '', title: 'HTML5 & Semantic Markup', level: 3, paragraph: 'Structuring accessible, SEO-friendly, and standard-compliant web document foundations.' },
          { id: '', title: 'CSS & Modern Layouts', level: 3, paragraph: 'Mastering Flexbox, Grid layouts, custom CSS properties, and responsive design systems.' },
          { id: '', title: 'JavaScript & Frameworks', level: 3, paragraph: 'Leveraging React, Vue, or Svelte alongside modern ES6+ features for interactive components.' },
          { id: '', title: 'Backend Systems & API Integration', level: 2, paragraph: 'Connecting frontend applications with REST APIs, GraphQL endpoints, and real-time WebSockets.' },
          { id: '', title: 'Database & Data Storage', level: 3, paragraph: 'Choosing between SQL relational databases and NoSQL document stores based on scalability needs.' },
          { id: '', title: 'Authentication & Security', level: 3, paragraph: 'Implementing OAuth2, JWT tokens, CORS policy, and defending against web vulnerabilities.' },
          { id: '', title: 'Performance & Optimization', level: 2, paragraph: 'Strategies for minimizing bundle sizes, optimizing asset delivery, and improving Core Web Vitals.' },
          { id: '', title: 'Testing & Quality Assurance', level: 2, paragraph: 'Automating tests using unit test runners, integration pipelines, and end-to-end testing frameworks.' },
          { id: '', title: 'CI/CD & Deployment', level: 2, paragraph: 'Automating builds, testing suites, containerization with Docker, and cloud platform deployments.' },
          { id: '', title: 'FAQs & Best Practices', level: 2, paragraph: 'Commonly asked questions regarding tech stack selection, project architecture, and code maintainability.' },
        ],
        containerWidth: '1140px',
        itemsGap: '12px',
        sidebarWidth: '320px',
        contentHeight: '85vh',

        sidebarBorder: { width: '1px', style: 'solid', color: '#e2e8f0', side: 'all' },
        sidebarBorderRadius: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
        headerBgColor: '#f9fafb',
        headerTextColor: '#1e293b',
        iconColor: '#64748b',
        sideHeaderTypography: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '600',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        headerIconSize: '20px',
        headerBorderWidth: {
          color: '#e5e7eb',
          width: '1px',
          style: 'solid',
          side: 'bottom',
        },
        sidebarBgColor: '#f9fafb',
        sidebarItemColor: '#475569',
        sidebarItemTypography: {
          fontSize: {
            desktop: '13px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        activeHeaderBgColor: '#1573d1',
        activeTextColor: '#ffffff',
        activeBorderLine: { color: '#00f03c', width: '4px', style: 'solid', side: 'left' },
        activeIconColor: '#0f172a',
        activeBorderRadius: { top: '0px', right: '4px', bottom: '4px', left: '0px' },
        sideTextIconSize: '18px',
        contentBgColor: '#f9fafb',
        contentBorderRadius: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
        contentBorder: { color: '#e5e7eb', width: '1px', style: 'solid', side: 'all' },
        contentHeaderTextColor: '#1e293b',
        contentHeaderTypography: {
          fontSize: {
            desktop: '28px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '800',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        contentHeaderBorderLine: {
          color: '#e5e7eb',
          width: '1px',
          style: 'solid',
          side: 'bottom',
        },
        contentDescriptionColor: '#6b7280',
        contentDescriptionTypography: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },

        contentTitleColor: '#111827',
        contentTitleTypography: {
          fontSize: {
            desktop: '20px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '400',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        contentParagraphColor: '#4b5563',
        contentParagraphTypography: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
      },
    },
  ],
};



