import { __ } from '@wordpress/i18n';
import { TemplateOneSvg } from './icons';

export const templateData = {
  title: __('Select Pricing Table Template', 'guten-builder-blocks'),
  subtitle: __('Choose a design template for your pricing grid.', 'guten-builder-blocks'),
  templates: [
    {
      id: 'template-1',
      label: __('Template 1', 'guten-builder-blocks'),
      tag: __('Standard Pricing Table', 'guten-builder-blocks'),
      icon: TemplateOneSvg,
      attributes: {
        pricingTables: [
          {
            name: __('Starter', 'guten-builder-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'guten-builder-blocks'),
            price: '20',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'guten-builder-blocks'),
            isFeatured: false,
            badgeText: '',
            featuresTitle: __("What's included:", 'guten-builder-blocks'),
            features: [
              { label: __('10 users', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('2GB of storage', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'guten-builder-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
              { label: __('Community access', 'guten-builder-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
            ],
          },
          {
            name: __('Pro', 'guten-builder-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'guten-builder-blocks'),
            price: '30',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'guten-builder-blocks'),
            isFeatured: true,
            badgeText: __('Popular', 'guten-builder-blocks'),
            featuresTitle: __("What's included:", 'guten-builder-blocks'),
            features: [
              { label: __('20 users', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('5GB of storage', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Community access', 'guten-builder-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
            ],
          },
          {
            name: __('Enterprise', 'guten-builder-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'guten-builder-blocks'),
            price: '100',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'guten-builder-blocks'),
            isFeatured: false,
            badgeText: '',
            featuresTitle: __("What's included:", 'guten-builder-blocks'),
            features: [
              { label: __('50 users', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('20GB of storage', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Community access', 'guten-builder-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
            ],
          },
        ],
        badgeRadius: {
          top: '1px',
          right: '1px',
          bottom: '1px',
          left: '16px',
        },
        featuredCardBorder: {
          color: '#4f46e5',
          width: '2px',
          style: 'solid',
          side: 'all',
        },
        featuredCardBg: { type: 'solid', color: '#f8fafc' },
        featuredCardBoxShadow: {
          hOffset: '0px',
          vOffset: '10px',
          blur: '15px',
          spread: '-3px',
          color: 'rgba(79, 70, 229, 0.1)',
        },
        cardBg: { type: 'solid', color: '#ffffff' },
        cardBorder: {
          color: '#e5e7eb',
          width: '1px',
          style: 'solid',
          side: 'all',
        },
        cardBoxShadow: {
          hOffset: '0px',
          vOffset: '4px',
          blur: '6px',
          spread: '-1px',
          color: 'rgba(0, 0, 0, 0.1)',
        },
        cardBorderRadius: {
          top: '8px',
          right: '8px',
          bottom: '8px',
          left: '8px',
        },
        cardTitleTypo: {},
        cardTitleColor: '#111827',
        cardDescTypo: {},
        cardDescColor: '#4b5563',
      },
    },
  ],
};
