import { __ } from '@wordpress/i18n';
import { TemplateOneSvg } from './icons';

export const templateData = {
  title: __('Select Pricing Table Template', 'xpo-blocks'),
  subtitle: __('Choose a design template for your pricing grid.', 'xpo-blocks'),
  templates: [
    {
      id: 'template-1',
      label: __('Template 1', 'xpo-blocks'),
      tag: __('Standard Pricing Table', 'xpo-blocks'),
      icon: TemplateOneSvg,
      attributes: {
        pricingTables: [
          {
            name: __('Starter', 'xpo-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'xpo-blocks'),
            price: '20',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'xpo-blocks'),
            isFeatured: false,
            badgeText: '',
            featuresTitle: __("What's included:", 'xpo-blocks'),
            features: [
              { label: __('10 users', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('2GB of storage', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'xpo-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
              { label: __('Community access', 'xpo-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
            ],
          },
          {
            name: __('Pro', 'xpo-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'xpo-blocks'),
            price: '30',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'xpo-blocks'),
            isFeatured: true,
            badgeText: __('Popular', 'xpo-blocks'),
            featuresTitle: __("What's included:", 'xpo-blocks'),
            features: [
              { label: __('20 users', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('5GB of storage', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Community access', 'xpo-blocks'), icon: 'fas-xmark', iconColor: '#ef4444' },
            ],
          },
          {
            name: __('Enterprise', 'xpo-blocks'),
            desc: __('Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'xpo-blocks'),
            price: '100',
            priceCurrency: '$',
            period: '/month',
            link: '#',
            isLinkNewTab: false,
            linkLabel: __('Get Started', 'xpo-blocks'),
            isFeatured: false,
            badgeText: '',
            featuresTitle: __("What's included:", 'xpo-blocks'),
            features: [
              { label: __('50 users', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('20GB of storage', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Email support', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Help center access', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Phone support', 'xpo-blocks'), icon: 'fas-check', iconColor: '#4338ca' },
              { label: __('Community access', 'xpo-blocks'), icon: 'fas-check', iconColor: '#ef4444' },
            ],
          },
        ],
        columns: 3,
        gap: 24,
        containerWidth: '1200px',

        badgeTypo: {
          fontSize: {
            desktop: '12px',
            tablet: '',
            mobile: '',
          },
          fontFamily: '',
          fontWeight: '700',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        badgeColor: {
          type: 'string',
          default: '#ffffff',
        },
        badgeBgColor: {
          type: 'string',
          default: '#4f46e5',
        },

        badgeRadius: {
          top: '1px',
          right: '1px',
          bottom: '1px',
          left: '16px',
        },

        //Popular
        featuredCardBorder: {
          color: '#4f46e5',
          width: '2px',
          style: 'solid',
          side: 'all',
        },
        featuredCardBg: { type: 'solid', color: '#f8fafc' },
        featuredCardBorderRadius: {
          top: '8px',
          right: '8px',
          bottom: '8px',
          left: '8px',
        },
        featuredCardBoxShadow: {
          hOffset: '0px',
          vOffset: '10px',
          blur: '15px',
          spread: '-3px',
          color: 'rgba(79, 70, 229, 0.1)',
        },
        featuredCardTitleTypo: {
          fontSize: {
            desktop: '18px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredCardTitleColor: '#111827',
        featuredCardDescTypo: {
          fontSize: {
            desktop: '15px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '300',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredCardDescColor: '#4b5563',
        featuredPriceColor: '#111827',
        featuredPriceTypo: {
          fontSize: {
            desktop: '36px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '700',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredPeriodTypo: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredButtonBg: '#4f46e5',
        featuredButtonHoverBg: '#fcfcfc',
        featuredButtonColor: '#ffffff',
        featuredButtonHoverColor: '#4f46e5',
        featuredButtonBorder: {
          color: '#4f46e5',
          width: '1px',
          style: 'solid',
          side: 'all',
        },
        featuredButtonRadius: {
          top: '2px',
          right: '2px',
          bottom: '2px',
          left: '2px',
        },
        featuredButtonTypo: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredDividerColor: '#e5e7eb',
        featuredFeaturesTitleColor: '#111827',
        featuredFeaturesTitleTypo: {
          fontSize: {
            desktop: '18px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featuredFeatureIconSize: 21,
        featuredFeatureTextColor: '#374151',
        featuredFeatureTextTypo: {
          fontSize: {
            desktop: '16px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '400',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },

        //Normal
        cardBg: { type: 'solid', color: '#ffffff' },
        cardBorder: {
          color: '#e5e7eb',
          width: '1px',
          style: 'solid',
          side: 'all',
        },
        cardBoxShadow: {
          hOffset: '0px',
          vOffset: '4px',
          blur: '6px',
          spread: '-1px',
          color: 'rgba(0, 0, 0, 0.1)',
        },
        cardBorderRadius: {
          top: '8px',
          right: '8px',
          bottom: '8px',
          left: '8px',
        },

        cardTitleTypo: {
          fontSize: {
            desktop: '18px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        cardTitleColor: '#111827',
        cardDescTypo: {
          fontSize: {
            desktop: '15px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '300',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        cardDescColor: '#4b5563',
        priceColor: '#111827',
        priceTypo: {
          fontSize: {
            desktop: '36px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '700',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        periodTypo: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        buttonBg: '#4f46e5',
        buttonHoverBg: '#fcfcfc',
        buttonColor: '#ffffff',
        buttonHoverColor: '#4f46e5',
        buttonBorder: {
          color: '#4f46e5',
          width: '1px',
          style: 'solid',
          side: 'all',
        },
        buttonRadius: {
          top: '2px',
          right: '2px',
          bottom: '2px',
          left: '2px',
        },
        buttonTypo: {
          fontSize: {
            desktop: '14px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        dividerColor: '#e5e7eb',
        featuresTitleColor: '#111827',
        featuresTitleTypo: {
          fontSize: {
            desktop: '18px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '500',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
        featureIconSize: 21,
        featureTextColor: '#374151',
        featureTextTypo: {
          fontSize: {
            desktop: '16px',
            tablet: '',
            mobile: '',
          },
          fontFamily: 'Google Sans Flex',
          fontWeight: '400',
          lineHeight: '',
          letterSpacing: '',
          textTransform: '',
          textDecoration: '',
          fontStyle: '',
        },
      },
    },
  ],
};
